package com.acre.ciu.model;

public enum Escolaridade {
	
	NAO_ALFABETIZADO,
	FUNDAMENTAL_INCOMPLETO,
	FUNDAMENTAL_COMPLETO,
	MEDIO_INCOMPLETO,
	MEDIO_COMPLETO,
	SUPERIOR_INCOMPLETO,
	SUPERIOR_COMPLETO,
	POS_GRADUACAO,
	EJA,
	NUNCA_FREQUENTOU,
	NAO_SE_APLICA

}
